version: '3.7'

services:
  ftp-server:
    image: fauria/vsftpd
    environment:
      FTP_USER: root
      FTP_PASS: root
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./ftpdata:/home/vsftpd
    networks:
      - ftp-network

networks:
  ftp-network:
    external: true
    name: ftp-network
