version: '3.8'  # Specifies the Docker Compose file version

services:
  minio:
    build: 
      context: ./minIO/Dockerfile
    ports:
      - "9000:9000"  # Exposes MinIO on port 9000
    volumes:
      - minio_data:/data  # Mounts the volume for MinIO data
    environment:
      MINIO_ROOT_USER: minioadmin  # Environment variable for MinIO root user
      MINIO_ROOT_PASSWORD: minioadmin  # Environment variable for MinIO root password
    restart: unless-stopped  # Ensures the service restarts unless it is stopped

volumes:
  minio_data:  # Declares a volume that can be reused
